# Generated by Django 5.2.7 on 2025-11-17 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20251111_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.CreateModel(
            name='ProductoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(help_text='ID único del usuario o IP para anónimos', max_length=100)),
                ('texto', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['producto', 'usuario_id', 'fecha_creacion'], name='catalogo_pr_product_2e5ab1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(help_text='ID único del usuario o IP para anónimos', max_length=100)),
                ('tipo', models.CharField(choices=[('like', 'Me gusta'), ('dislike', 'No me gusta')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Like/Dislike',
                'verbose_name_plural': 'Likes/Dislikes',
                'unique_together': {('producto', 'usuario_id')},
            },
        ),
    ]
