# Generated by Django 5.2.7 on 2025-11-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_producto_orden_productocomentario_productolike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
